spring.application.name=api

spring.datasource.url=jdbc:mysql://localhost/finance_ia
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

#Le dice a Hibernate cómo generar SQL para tu base de datos
hibernite.dialect=org.hibernate.dialect.HSQLDialect

#Bases de datos
#Muestra las queries SQL en consola
spring.jpa.show-sql=true
spring.jpa.format-sql=true

# Configuración de JPA, actualiza cualquier cambio
#spring.jpa.hibernate.ddl-auto=update

#Controla cómo se formatea la respuesta JSON cuando usas paginación
spring.data.web.pageable.page-serialization-mode=via_dto

# --- CONFIGURACIÓN DE SWAGGER / OPENAPI (SPRINGDOC) ---

# Ruta para obtener la especificación de la API en formato JSON (Por defecto: /v3/api-docs)
springdoc.api-docs.path=/api-docs
# URL de acceso a la interfaz gráfica interactiva de Swagger UI (Por defecto: /swagger-ui.html)
springdoc.swagger-ui.path=/swagger-ui.html
# Ordena los endpoints en la interfaz alfabéticamente por su método HTTP (GET, POST, PUT, DELETE)
springdoc.swagger-ui.operationsSorter=method

# --- NUMERO MAXIMO DE RECOMENDACIONES ---
recommendation.max-recommendations=3
