spring.application.name=api

spring.datasource.url=jdbc:mysql://localhost/finance_ia
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Le dice a Hibernate c\u00F3mo generar SQL para tu base de datos
#hibernite.dialect=org.hibernate.dialect.HSQLDialect

#Bases de datos
#Muestra las queries SQL en consola
spring.jpa.show-sql=true
spring.jpa.format-sql=true

# Configuraci\u00F3n de JPA, actualiza cualquier cambio
spring.jpa.hibernate.ddl-auto=update

# L\u00EDmites de tama\u00F1o para la carga de archivos
spring.servlet.multipart.max-file-size=100MB
spring.servlet.multipart.max-request-size=100MB

#Controla c\u00F3mo se formatea la respuesta JSON cuando usas paginaci\u00F3n
spring.data.web.pageable.page-serialization-mode=via_dto

# --- CONFIGURACI\u00D3N DE SWAGGER / OPENAPI (SPRINGDOC) ---

# Ruta para obtener la especificaci\u00F3n de la API en formato JSON (Por defecto: /v3/api-docs)
springdoc.api-docs.path=/api-docs
# URL de acceso a la interfaz gr\u00E1fica interactiva de Swagger UI (Por defecto: /swagger-ui.html)
springdoc.swagger-ui.path=/swagger-ui.html
# Orden de los grupos de endpoints en Swagger UI
springdoc.swagger-ui.tagsSorter=alpha
# Ordena los endpoints/m\u00E9todos dentro de la etiqueta por su operationId/nombre
springdoc.swagger-ui.operationsSorter=alpha


# --- NUMERO MAXIMO DE RECOMENDACIONES ---
recommendation.max-recommendations=3
